In [1]:
import pandas as pd

In [9]:
data_df = pd.read_csv('forms.csv')
data_df

,ID,Local_ID,Language_ID,Parameter_ID,Value,Form,Segments,Comment,Source,Cognacy,Loan,Graphemes,Profile,Prosody,Morpheme_Glosses,Partial_Cognacy,Chinese_Characters
0,Beijing-91_vomit-1,NaN,Beijing,91_vomit,tʰu⁵¹,tʰu⁵¹,tʰ u ⁵¹,NaN,Liu2007,NaN,NaN,NaN,NaN,i n t,spit/吐,1,吐
1,Haerbin-91_vomit-1,NaN,Haerbin,91_vomit,tʰu⁵³,tʰu⁵³,tʰ u ⁵³,NaN,Liu2007,NaN,NaN,NaN,NaN,i n t,spit/吐,1,吐
2,Jinan-91_vomit-1,NaN,Jinan,91_vomit,tʰu³¹,tʰu³¹,tʰ u ³¹,NaN,Liu2007,NaN,NaN,NaN,NaN,i n t,spit/吐,1,吐
3,Rongcheng-91_vomit-1,NaN,Rongcheng,91_vomit,ou²¹³⁻³⁵ tʰu²¹⁴,ou²¹³⁻³⁵ tʰu²¹⁴,ou ²¹³ + tʰ u ²¹⁴,copulative synonyme,Liu2007,NaN,NaN,NaN,NaN,n t + i n t,nausea/嘔 spit/吐,2 1,嘔 吐
4,Taiyuan-91_vomit-1,NaN,Taiyuan,91_vomit,tʰu⁵³ lə⁰,tʰu⁵³ lə⁰,tʰ u ⁵³ + l ə ⁰,NaN,Liu2007,NaN,NaN,NaN,NaN,i n t + i n t,nausea/嘔 _:PERFECTIVE/了,2 5,嘔 嘞
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4297,Guangzhou-90_woman-1,NaN,Guangzhou,90_woman,nøy²³ iɐn²¹⁻²³,nøy²³ iɐn²¹⁻²³,n øy ²³ + j ɐ n ²¹,NaN,Liu2007,NaN,NaN,NaN,NaN,i n t + i n c t,female/女 _person/人,39 38,女 人
4298,Fuzhou-90_woman-1,NaN,Fuzhou,90_woman,i⁵⁵⁻⁵³ tsia³²,i⁵⁵⁻⁵³ tsia³²,i ⁵⁵ + ts j a ³²,NaN,Liu2007,NaN,NaN,NaN,NaN,n t + i m n t,woman/伊 sister/姐,824 715,伊 姐
4299,Fuzhou-90_woman-2,NaN,Fuzhou,90_woman,ny³²⁻⁵⁵ ɛ²¹²,ny³²⁻⁵⁵ ɛ²¹²,n y ³² + ɛ ²¹²,NaN,Liu2007,NaN,NaN,NaN,NaN,i n t + n t,female/女 _world/界,39 825,女 界
4300,Fuzhou-90_woman-3,NaN,Fuzhou,90_woman,tsy⁵⁵ nøyŋ⁵³⁻⁵⁵ nøyŋ⁵³,tsy⁵⁵ nøyŋ⁵³⁻⁵⁵ nøyŋ⁵³,ts y ⁵⁵ + n øy ŋ ⁵³ + n øy ŋ ⁵³,NaN,Liu2007,NaN,NaN,NaN,NaN,i n t + i n c t + i n c t,woman/諸 female/娘 _person/人,749 31 38,諸 娘 儂
4301,Xiamen-90_woman-1,NaN,Xiamen,90_woman,tsa⁵⁵⁻²² bɔ⁵³⁻⁵⁵ laŋ²⁴,tsa⁵⁵⁻²² bɔ⁵³⁻⁵⁵ laŋ²⁴,ts a ⁵⁵ + b ɔ ⁵³ + l a ŋ ²⁴,NaN,Liu2007,NaN,NaN,NaN,NaN,i n t + i n t + i n c t,woman/查 wife/某 _person/人,750 53 38,查 某 人

step 1 extract all the parameter_ID/ Language_ID to decide how many words we are inverstigating

In [32]:
# 19 cities 
cities = data_df['Language_ID'].unique()
cities

array(['Beijing', 'Haerbin', 'Jinan', 'Rongcheng', 'Taiyuan', 'XiAn',
       'Chengdu', 'Nanjing', 'Jixi', 'Suzhou', 'Wenzhou', 'Changsha',
       'Loudi', 'Nanchang', 'Meixian', 'Guilin', 'Guangzhou', 'Fuzhou',
       'Xiamen'], dtype=object)

In [34]:
# 203 words 
words = data_df['Parameter_ID'].unique()
words

array(['91_vomit', '92_fear', '93_skin', '94_float', '95_smooth',
       '96_wife', '97_all', '98_hot', '99_person', '100_throw', '1_white',
       '2_back', '3_nose', '4_ice', '5_neck', '6_thin', '7_not', '8_rub',
       '9_grass', '10_long', '101_flesh', '102_if', '103_breasts',
       '104_three', '105_woods', '106_kill', '107_sand', '108_mountain',
       '109_burn', '110_few', '111_tongue', '112_snake', '113_rope',
       '114_louse', '115_wet', '116_what', '117_stone', '118_hand',
       '119_tree', '120_bark', '121a_countnoun', '121b_countverb',
       '122_who', '123_water', '124_fruit', '125_sleep', '126_suck',
       '127_say', '128_split', '129_die', '130_four', '131_he',
       '132_they', '133_sun', '134_lie', '135_day', '136_sky', '137_hear',
       '138_head', '139_hair', '140_earth', '141_spit', '142_push',
       '143_leg', '144_dig', '145_play', '146_night', '147_tail',
       '148_smell', '149_i', '150_we', '151_five', '152_fog', '153_knee',
       '154_wash', '155_think', '156_small', '157_laugh', '158_heart',
       '202_heartcompound', '159_new', '160_star', '161_snow',
       '162_blood', '163_squeeze', '164_tooth', '165_smoke', '166_salt',
       '167_eye', '168_bite', '169_leaf', '170_one', '171_because',
       '172_swim', '173_rightside', '174_fish', '175_feather', '176_rain',
       '177_round', '178_far', '179_moon', '180_cloud', '181_in',
       '182_dirty', '183_how', '184_narrow', '185_stand', '186_husband',
       '187_this', '188_here', '189_know', '190_grease', '191_straight',
       '192_swell', '193_seed', '194_heavy', '195_scratch', '196_claw',
       '197_turn', '198_walk', '199_mouth', '200_leftside', '201_sit',
       '11_guts', '12_sing', '13_dust', '14_eat', '15_wing', '16_worm',
       '17_blow', '18_stab', '19_hit', '20_fight', '21_hunt', '22_big',
       '23_dull', '24_fall', '25_animal', '26_belly', '27_short',
       '28_correct', '29_many', '30_ear', '31_two', '32_fly', '33_wind',
       '34_sew', '35_rotten', '36_father', '37_dry', '38_liver',
       '39_give', '40_root', '41_dog', '42_bone', '43_stick', '44_child',
       '45_sea', '46_good', '47_drink', '48_and', '49_river', '50_river',
       '51_black', '52_red', '53_thick', '54_breathe', '55_lake',
       '56_flower', '57_bad', '58_yellow', '59_ash', '60_livealive',
       '61_fire', '62_egg', '63_sharp', '64_horn', '65_foot', '66_freeze',
       '67_near', '68_cut', '69_see', '70_wide', '71_tie', '72_pull',
       '73_come', '74_old', '75_cold', '76_flow', '77_path', '78_green',
       '79_full', '80_name', '81_mather', '82_holdtake', '83_where',
       '84_that', '85_there', '86_man', '87_you', '88_year', '89_bird',
       '90_woman'], dtype=object)

In [35]:
len(words)

203

step 2 under the same word, test the value/form/segements difference among different areas

But with what method to calculate the phonetics difference? Use value /Form or Segments

step3 Raise some questions related with the dialetcs' geography and explore it